[project]
name = "mwx"
version = "0.1.0"
description = "QoL tool for MyWallet Android app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["black>=25.1.0", "pytest>=8.4.1", "ruff>=0.12.9"]

[tool.ruff.lint]
ignore = ["F401"]
